In [ ]:
from google.colab import drive
drive.mount("/content/drive")

Mounted at /content/drive


In [ ]:
import numpy as np
import pandas as pd
from sklearn import neighbors, metrics
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder


In [ ]:
data = pd.read_csv('/content/drive/MyDrive/Demo-Algorithms-ML/car.data')
print(data.head())

  buying  maint doors persons lug_boot safety  class
0  vhigh  vhigh     2       2    small    low  unacc
1  vhigh  vhigh     2       2    small    med  unacc
2  vhigh  vhigh     2       2    small   high  unacc
3  vhigh  vhigh     2       2      med    low  unacc
4  vhigh  vhigh     2       2      med    med  unacc


In [ ]:
X = data[['buying','maint','safety']].values
#label
y = data[['class']]

#converting the data from string to int
#X
Le = LabelEncoder()
for i in range(len(X[0])):
  X[:,i] = Le.fit_transform(X[:, i])
print(X)

[[3 3 1]
 [3 3 2]
 [3 3 0]
 ...
 [1 1 1]
 [1 1 2]
 [1 1 0]]


In [ ]:
#y
label_mapping = {'unacc':0,
                 'acc' : 1,
                 'good': 2,
                 'vgood':3}
y['class'] = y['class'].map(label_mapping)
y = np.array(y)
print(y)

[[0]
 [0]
 [0]
 ...
 [0]
 [2]
 [3]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:6: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  


In [ ]:
#Create Model - 
# 1. KNN
knn = neighbors.KNeighborsClassifier(n_neighbors = 25, weights='uniform')
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2)
knn.fit(X_train, y_train)


/usr/local/lib/python3.7/dist-packages/sklearn/neighbors/_classification.py:198: DataConversionWarning: A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples,), for example using ravel().
  return self._fit(X, y)


KNeighborsClassifier(n_neighbors=25)

In [ ]:
prediction = knn.predict(X_test)
accuracy = metrics.accuracy_score(y_test, prediction)
print("Predictions : ",prediction)
print("accuracy: ",accuracy)

Predictions :  [0 0 0 0 1 3 0 1 0 0 3 0 0 3 1 0 1 1 0 0 0 0 0 0 0 0 0 1 0 0 1 0 0 0 0 1 1
 0 0 0 1 0 0 1 0 0 0 1 0 1 0 0 0 0 0 0 1 0 0 3 1 1 0 0 0 1 1 0 1 0 0 0 0 1
 0 0 0 3 0 0 0 1 0 1 1 1 3 0 3 0 0 0 0 0 0 0 1 0 0 0 1 0 0 0 0 0 0 0 0 0 0
 0 0 3 0 0 3 0 1 0 0 0 0 0 0 3 1 0 3 1 1 0 0 0 1 0 0 0 0 0 1 0 0 0 1 1 0 0
 0 1 0 3 0 3 1 0 0 1 0 3 0 0 0 3 0 3 0 0 0 0 1 1 0 1 0 1 0 0 0 3 0 0 1 1 0
 0 0 0 1 1 0 3 0 3 0 0 0 0 1 0 1 0 1 0 0 3 0 0 0 0 0 1 0 0 3 0 1 0 0 1 0 1
 0 0 0 0 0 1 0 0 1 1 1 1 0 0 1 0 0 0 1 3 0 0 0 0 1 1 0 0 0 0 0 0 1 0 0 0 0
 1 0 0 0 1 0 0 0 0 0 0 0 0 3 1 0 1 0 0 0 0 0 0 0 0 0 0 3 0 1 0 0 0 0 0 1 0
 1 0 0 0 3 1 0 0 1 0 0 0 0 0 0 0 0 0 0 1 0 0 0 3 0 0 0 1 0 0 0 0 0 0 0 0 0
 1 0 0 1 1 0 0 0 0 1 0 0 1]
accuracy:  0.7398843930635838


In [ ]:
#checking for prediction and actual val
a = 89
print("Actual val : ",y[a])
print("predicted val: ",knn.predict(X)[a])

Actual val :  [0]
predicted val:  0
